   
        function chargerCommunes() {
            const wilayaSelect = document.getElementById("wilaya");
            const communeSelect = document.getElementById("commune");
            const selectedWilaya = wilayaSelect.value;

            // Effacer les options précédentes
            communeSelect.innerHTML = '';

            
            // liste des communes par wilaya.
            const communes = {
			"01- Adrar": ["Choisir Commune", "Adrar", "Akabli", "Aoulef", "Bouda", "Fenoughil", "In Zghmir", "Ouled Ahmed Tammi", "Reggane", "Sali", "Sebaa", "Tamantit", "Tamekten", "Tamest", "Tit", "Tsabit", "Zaouiet Kounta"],
            "02- Chlef": ["Choisir Commune", "Abou El Hassan", "Aïn Merane", "Bénairia", "Beni Bouateb", "Beni Haoua", "Beni Rached", "Boukadir", "Bouzeghaia", "Breira", "Chettia", "Chlef", "Dahra", "El Hadjadj", "El Karimia", "El Marsa", "Harchoun", "Harenfa", "Labiod Medjadja", "Moussadek", "Oued Fodda", "Oued Goussine", "Oued Sly", "Ouled Abbes", "Ouled Ben Abdelkader", "Ouled Fares", "Oum Drou", "Sendjas", "Sidi Abderrahmane", "Sidi Akkacha", "Sobha", "Tadjena", "Talassa", "Taougrite", "Ténès", "Zeboudja"],
			"03- Laghouat": ["Choisir Commune", "Aflou", "Aïn Madhi", "Aïn Sidi Ali (Non livrable)", "Beidha (Non livrable)", "Bennasser Benchohra", "Brida (Non livrable)", "El Assafia", "El Ghicha", "El Houaita", "Gueltat Sidi Saad", "Hadj Mechri (Non livrable)", "Hassi Delaa", "Hassi R'Mel", "Kheneg", "Ksar El Hirane", "Laghouat", "Oued M'Zi", "Oued Morra (Non livrable)", "Sebgag (Non livrable)", "Sidi Bouzid (Non livrable)", "Sidi Makhlouf", "Tadjemout", "Tadjrouna (Non livrable)", "Taouiala (Non livrable)"],
			"04- Oum El Bouaghi": ["Choisir Commune", "Aïn Babouche", "Aïn Beïda", "Aïn Diss", "Aïn Fakroun", "Aïn Kercha", "Aïn M'lila", "Aïn Zitoun", "Behir Chergui", "Berriche", "Bir Chouhada", "Dhalaa", "El Amiria", "El Belala", "El Djazia", "El Fedjoudj Boughrara Saoudi", "El Harmilia", "Fkirina", "Hanchir Toumghani", "Ksar Sbahi", "Meskiana", "Oued Nini", "Ouled Gacem", "Ouled Hamla", "Ouled Zouaï", "Oum el Bouaghi", "Rahia", "Sigus", "Souk Naamane", "Zorg"],
			"05- Batna": ["Choisir Commune", "Abdelkader Azil", "Aïn Djasser", "Aïn Touta", "Aïn Yagout", "Arris", "Barika", "Batna", "Ben Foudhala El Hakania", "Bitam", "Boulhilat", "Boumagueur", "Boumia (Batna)", "Bouzina", "Chemora", "Chir", "Djerma", "Djezar", "El Hassi", "El Madher", "Fesdis", "Foum Toub", "Ghassira", "Gosbat (Non livrable)", "Guigba", "Hidoussa", "Ichmoul", "Inoughissen", "Kimmel", "Ksar Bellezma", "Larbaâ (Non livrable)", "Lazrou", "Lemsane", "M'doukel", "Maafa", "Menaa", "Merouana", "N'Gaous", "Oued Chaaba", "Oued El Ma", "Oued Taga", "Ouled Ammar (Non livrable)", "Ouled Aouf", "Ouled Fadel", "Ouled Sellam", "Ouled Si Slimane", "Ouyoun El Assafir", "Rahbat", "Ras El Aioun", "Sefiane", "Seggana", "Seriana", "T'Kout", "Talkhamt", "Taxlent", "Tazoult", "Teniet El Abed", "Tighanimine", "Tigherghar", "Tilatou", "Timgad", "Zanat El Beida"],
			"06- Béjaïa": ["Choisir Commune", "Adekar", "Ait Djellil", "Aït Ksila", "Aït Maouche", "Aït Mellikeche", "Aït R'zine", "Aït Smail", "Akbou", "Akfadou", "Amalou", "Amizour", "Aokas", "Barbacha", "Béjaïa", "Boudjellil", "Bouhamza", "Boukhelifa", "Chellata", "Chemini", "Darguina", "Draâ El Kaïd", "El Kseur", "Fenaïa Ilmaten", "Ferraoun", "Ighil Ali", "Ighram", "Kendira", "Kherrata", "Leflaye", "M'cisna", "Melbou", "Oued Ghir", "Ouzellaguen", "Seddouk", "Semaoun", "Sidi Aïch", "Sidi Ayad", "Souk El Ténine", "Souk Oufella", "Tala Hamza", "Tamokra (Non livrable)", "Tamridjet", "Taourirt Ighil", "Taskriout", "Tazmalt", "Tibane", "Tichy", "Tifra", "Timezrit 06", "Tinabdher", "Tizi N'Berber (Non livrable)", "Toudja" ],
			"07- Biskra": ["Choisir Commune", "Aïn Naga", "Aïn Zaatout", "Biskra", "Bordj Ben Azzouz", "Bouchagroune", "Branis", "Chetma", "Djemorah", "El Feidh", "El Ghrous", "El Hadjeb", "El Haouch", "El Kantara", "El Mizaraa", "El Outaya", "Foughala", "Khenguet Sidi Nadji", "Lichana", "Lioua", "M'Chouneche", "M'Lili", "Mekhadma", "Oumache", "Ourlal", "Sidi Okba", "Tolga", "Zeribet El Oued"],
			"08- Béchar": ["Choisir Commune", "Abadla", "Béchar", "Beni Ounif", "Boukais (Non livrable)","Erg Ferradj", "Kenadsa", "Lahmar (Non livrable)","Mechraa Houari Boumedienne", "Meridja", "Mougheul", "Taghit"],
			"09- Blida": ["Choisir Commune", "Aïn Romana", "Beni Mered", "Beni Tamou", "Benkhelil", "Blida", "Bouarfa", "Boufarik", "Bougara 09", "Bouinan", "Chebli", "Chiffa", "Chréa", "Djebabra", "El Affroun", "Guerouaou", "Hammam Melouane", "Larbaa", "Meftah", "Mouzaia", "Oued Alleug", "Oued Djer", "Ouled Slama", "Ouled Yaïch", "Souhane", "Soumaa"],
			"10- Bouira": ["Choisir Commune", "Aghbalou", "Ahl El Ksar", "Aïn Bessem", "Aïn El Hadjar 10", "Aïn El Turc", "Aïn Laloui", "Aït Laziz", "Aomar", "Ath Mansour", "Bechloul", "Bir Ghbalou", "Bordj Okhriss (Non livrable)", "Bouderbala", "Bouira", "Boukram (Non livrable)", "Chorfa 10", "Dechmia (Non livrable)", "Dirrah (Non livrable)", "Djebahia", "El Adjiba", "El Asnam", "El Hachimia", "El Hakimia (Non livrable)", "El Khabouzia", "El Mokrani", "Guerrouma (Non livrable)", "Hadjera Zerga (Non livrable)", "Haizer", "Hanif", "Kadiria", "Lakhdaria", "M'Chedallah", "Maala (Non livrable)", "Maamora (Non livrable)", "Mezdour (Non livrable)", "Oued El Berdi", "Ouled Rached", "Raouraoua", "Ridane (Non livrable)", "Saharidj", "Souk El Khemis", "Sour El Ghouzlane", "Taghzout 10", "Taguedit (Non livrable)", "Zbarbar (Non livrable)"],
			"11- Tamanrasset": ["Choisir Commune", "Abalessa (Non livrable)", "Idles (Non livrable)", "In Amguel (Non livrable)", "Tamanrasset", "Tazrouk (Non livrable)"],
			"12- Tébessa": ["Choisir Commune", "Aïn Zerga", "Bedjene", "Bekkaria", "Bir Dheb", "Bir el Ater (Non livrable)", "Bir Mokkadem", "Boukhadra", "Boulhaf Dir", "Cheria", "El Aouinet", "El Houidjbet", "El Kouif", "El Ma Labiodh", "El Meridj", "El Mezeraa", "El Ogla 12", "Ferkane", "Guorriguer", "Hammamet", "Morsott", "Negrine", "Ogla Melha", "Ouenza", "Oum Ali", "Safsaf El Ouesra", "Stah Guentis", "Tébessa", "Tlidjene"],
			"13- Tlemcen": ["Choisir Commune", "Aïn Fetah", "Aïn Fezza", "Aïn Ghoraba", "Aïn Kebira", "Aïn Nehala", "Aïn Tallout", "Aïn Youcef", "Amieur", "Azails", "Bab El Assa", "Beni Bahdel", "Beni Boussaid", "Beni Khellad", "Beni Mester", "Beni Ouarsous", "Beni Semiel", "Beni Snous", "Bensekrane", "Bouhlou", "Chetouane", "Dar Yaghmouracene", "Djebala", "El Aricha", "El Bouihi", "El Fehoul", "El Gor", "Fellaoucene", "Ghazaouet", "Hammam Boughrara", "Hennaya", "Honaïne", "Maghnia", "Mansourah 13", "Marsa Ben M'Hidi", "MSirda Fouaga", "Nedroma", "Oued Lakhdar", "Ouled Mimoun", "Ouled Riyah", "Remchi", "Sabra", "Sebaa Chioukh", "Sebdou", "Sidi Abdelli", "Sidi Djillali", "Sidi Medjahed", "Souahlia", "Souani", "Souk Tlata", "Terny Beni Hdiel", "Tienet", "Tlemcen", "Zenata"],
			"14- Tiaret": ["Choisir Commune", "Aïn Bouchekif", "Aïn Deheb", "Aïn Dzarit", "Aïn El Hadid", "Aïn Kermes", "Bougara 14", "Chehaima", "Dahmouni", "Djebilet Rosfa", "Djillali Ben Amar", "Faidja", "Frenda", "Guertoufa", "Hamadia", "Ksar Chellala", "Madna (Non livrable)", "Mahdia", "Mechraa Safa", "Medrissa", "Medroussa", "Meghila", "Mellakou", "Nadorah (Non livrable)", "Naima", "Oued Lilli", "Rahouia", "Rechaiga", "Sebaine", "Sebt", "Serghine", "Si Abdelghani", "Sidi Abderahmane", "Sidi Ali Mellal", "Sidi Bakhti (Non livrable)", "Sidi Hosni", "Sougueur", "Tagdemt", "Takhemaret", "Tiaret", "Tidda", "Tousnina", "Zmalet El Emir Abdelkader"],
			"15- Tizi Ouzou": ["Choisir Commune", "Abi Youcef", "Aghribs", "Agouni Gueghrane", "Ain El Hammam", "Aïn Zaouia", "Aït Aggouacha", "Aït Aïssa Mimoun", "Aït Bouadou", "Aït Boumahdi", "Aït Chafâa", "Aït Khellili", "Aït Mahmoud", "Aït Oumalou", "Aït Toudert", "Aït Yahia", "Aït Yahia Moussa", "Aït Yenni", "Akbil", "Akerrou", "Assi Youcef", "Ath Zikki", "Azazga", "Azeffoun", "Beni Aïssi", "Beni Douala", "Beni Zmenzer", "Boghni", "Boudjima", "Bounouh", "Bouzguen", "Draâ Ben Khedda", "Draâ El Mizan", "Freha", "Frikat", "Iboudraren", "Idjeur", "Iferhounène", "Ifigha", "Iflissen", "Illilten", "Illoula Oumalou", "Imsouhel", "Irdjen", "Larbaâ Nath Irathen", "M'Kira", "Mâatkas", "Makouda", "Mechtras", "Mekla", "Mizrana", "Ouacif", "Ouadhia", "Ouaguenoun", "Sidi Namane", "Souamaâ", "Souk El Thenine", "Tadmaït", "Tigzirt", "Timizart", "Tirmitine", "Tizi Gheniff", "Tizi N'Tleta", "Tizi Ouzou", "Tizi Rached", "Yakouren", "Yatafen", "Zekri (Non livrable)"],
			"16- Alger": ["Choisir Commune", "Aïn Benian 16", "Aïn Taya", "Alger Centre", "Bab El Oued", "Bab Ezzouar", "Baba Hassen", "Bachdjerrah", "Baraki", "Belouizdad", "Ben Aknoun", "Beni Messous", "Bir Mourad Raïs", "Birkhadem", "Birtouta", "Bologhine", "Bordj El Bahri", "Bordj El Kiffan", "Bourouba", "Bouzareah", "Casbah", "Cheraga", "Dar El Beïda", "Dely Ibrahim", "Djasr Kasentina", "Douera", "Draria", "El Achour", "El Biar", "El Hammamet", "El Harrach", "El Madania", "El Magharia", "El Marsa", "El Mouradia", "H'raoua", "Hussein Dey", "Hydra", "Khraicia", "Kouba", "Les Eucalyptus", "Mahelma", "Mohammadia 16", "Oued Koriche", "Oued Smar", "Ouled Chebel", "Ouled Fayet", "Rahmania", "Raïs Hamidou", "Reghaïa", "Rouïba", "Saoula", "Sidi M'Hamed 16", "Sidi Moussa", "Souidania", "Staoueli", "Tessala El Merdja", "Zeralda"],
			"17- Djelfa": ["Choisir Commune", "Aïn Chouhada (Non livrable)", "Aïn El Ibel", "Aïn Feka", "Aïn Maabed", "Aïn Oussara", "Amourah (Non livrable)", "Benhar", "Beni Yagoub", "Birine", "Bouira Lahdab", "Charef", "Dar Chioukh", "Deldoul", "Djelfa", "Douis", "El Guedid", "El Idrissia", "El Khemis", "Faidh El Botma (Non livrable)", "Guernini (Non livrable)", "Guettara (Non livrable)", "Had Sahary", "Hassi Bahbah", "Hassi El Euch", "Hassi Fedoul", "M'Liliha (Non livrable)", "Messaad", "Moudjebara", "Oum Laadham (Non livrable)", "Sed Rahal (Non livrable)", "Selmana (Non livrable)", "Sidi Baizid (Non livrable)", "Sidi Ladjel", "Tadmit (Non livrable)", "Zaafrane (Non livrable)", "Zaccar"],
			"18- Jijel": ["Choisir Commune", "Bordj Tahar", "Boucif Ouled Askeur (Non livrable)", "Boudriaa Ben Yadjis", "Bouraoui Belhadef", "Chahna", "Chekfa", "Djemaa Beni Habibi", "Djimla", "El Ancer", "El Aouana", "El Kennar Nouchfi", "El Milia", "Emir Abdelkader", "Eraguene (Non livrable)", "Ghebala", "Jijel", "Kaous", "Kheïri Oued Adjoul", "Ouadjana", "Ouled Rabah (Non livrable)", "Ouled Yahia Khedrouche", "Selma Benziada (Non livrable)", "Settara", "Sidi Abdelaziz", "Sidi Maarouf", "Taher", "Texenna", "Ziama Mansouriah"],
			"19- Sétif": ["Choisir Commune", "Aïn Abessa", "Aïn Arnat", "Aïn Azel", "Aïn El Kebira", "Aïn Lahdjar", "Aïn Legradj", "Aïn Oulmene", "Aïn Roua", "Aïn Sebt", "Aït Naoual Mezada", "Aït Tizi", "Aït Wertilan", "Amoucha", "Babor", "Bazer Sakhra", "Beidha Bordj", "Belaa", "Beni Aziz", "Beni Chebana", "Beni Fouda", "Beni Hocine", "Beni Mouhli", "Bir El Arch", "Bir Haddada", "Bouandas", "Bougaa", "Bousselam", "Boutaleb", "Dehamcha", "Djemila", "Draa Kebila", "El Eulma", "El Ouldja 19", "El Ouricia", "Guellal", "Guelta Zerka", "Guenzet", "Guidjel", "Hamma", "Hammam Guergour", "Hammam Soukhna", "Harbil", "Ksar El Abtal", "Maaouia", "Maoklane", "Mezloug", "Oued El Barad", "Ouled Addouane", "Ouled Sabor", "Ouled Si Ahmed", "Ouled Tebben", "Rasfa", "Salah Bey", "Serdj El Ghoul", "Sétif", "Tachouda", "Talaifacene", "Taya", "Tella", "Tizi N'Bechar"],
			"20- Saïda": ["Choisir Commune", "Aïn El Hadjar 20", "Aïn Sekhouna (Non livrable)", "Aïn Soltane 20", "Doui Thabet", "El Hassasna", "Hounet (Non livrable)", "Maamora", "Moulay Larbi", "Ouled Brahim 20", "Ouled Khaled", "Saïda", "Sidi Ahmed", "Sidi Amar 20", "Sidi Boubekeur", "Tircine", "Youb"],
			"21- Skikda": ["Choisir Commune", "Aïn Bouziane", "Aïn Charchar", "Aïn Kechra", "Aïn Zouit", "Azzaba", "Bekkouche Lakhdar", "Ben Azzouz", "Beni Bechir", "Beni Oulbane", "Beni Zid", "Bin El Ouiden", "Bouchtata", "Cheraia", "Collo", "Djendel Saadi Mohamed", "El Ghedir", "El Hadaiek", "El Harrouch", "El Marsa (Non livrable)", "Emdjez Edchich", "Es Sebt", "Filfila", "Hamadi Krouma", "Kanoua", "Kerkera", "Kheneg Mayoum", "Oued Zehour", "Ouldja Boulballout", "Ouled Attia", "Ouled Hbaba", "Oum Toub", "Ramdane Djamel", "Salah Bouchaour", "Sidi Mezghiche", "Skikda", "Tamalous", "Zerdaza", "Zitouna"],
			"22- Sidi Bel Abbès": ["Choisir Commune", "Aïn Adden", "Aïn El Berd", "Aïn Kada", "Aïn Thrid", "Aïn Tindamine", "Amarnas", "Badredine El Mokrani", "Belarbi", "Ben Badis", "Benachiba Chelia", "Bir El Hammam", "Boudjebaa El Bordj", "Boukhanafis", "Chettouane Belaila", "Dhaya", "El Haçaiba", "Hassi Dahou", "Hassi Zehana", "Lamtar", "M'Cid", "Makedra", "Marhoum", "Merine", "Mezaourou", "Mostefa Ben Brahim", "Moulay Slissen", "Oued Sebaa", "Oued Sefioun", "Oued Taourira", "Ras El Ma", "Redjem Demouche", "Sehala Thaoura", "Sfisef", "Sidi Ali Benyoub", "Sidi Ali Boussidi", "Sidi Bel Abbes", "Sidi Brahim", "Sidi Chaib", "Sidi Daho des Zairs", "Sidi Hamadouche", "Sidi Khaled", "Sidi Lahcene", "Sidi Yacoub", "Tabia", "Tafissour", "Taoudmout", "Teghalimet", "Telagh", "Tenira", "Tessala", "Tilmouni", "Zerouala"],	
			"23- Annaba": ["Choisir Commune", "Aïn Berda", "Annaba", "Berrahal", "Chetaïbi", "Cheurfa", "El Bouni", "El Hadjar", "Eulma", "Oued El Aneb", "Seraïdi", "Sidi Amar 23", "Treat"],
			"24- Guelma": ["Choisir Commune", "Aïn Ben Beida", "Aïn Larbi", "Aïn Makhlouf", "Aïn Reggada", "Aïn Sandel", "Belkheir", "Ben Djerrah", "Beni Mezline", "Bordj Sabath", "Bouati Mahmoud", "Bouchegouf", "Bouhachana", "Bouhamdane", "Boumahra Ahmed", "Dahouara", "Djeballah Khemissi", "El Fedjoudj", "Guellat Bou Sbaa", "Guelma", "Hammam Debagh", "Hammam N'Bail", "Héliopolis", "Houari Boumédiène", "Khezarra", "Medjez Amar", "Medjez Sfa", "Nechmaya", "Oued Cheham", "Oued Fragha", "Oued Zenati", "Ras El Agba", "Roknia", "Sellaoua Announa", "Tamlouka"],
			"25- Constantine": ["Choisir Commune", "Aïn Abid", "Aïn Smara", "Beni Hamiden", "Constantine", "Didouche Mourad", "El Khroub", "Hamma Bouziane", "Ibn Badis", "Ibn Ziad", "Messaoud Boudjriou", "Ouled Rahmoune", "Zighoud Youcef"],
			"26- Médéa": ["Choisir Commune", "Aïn Boucif", "Aïn Ouksir (Non livrable)", "Aissaouia", "Aziz", "Baata", "Benchicao", "Beni Slimane", "Berrouaghia", "Bir Ben Laabed", "Boghar", "Bou Aiche", "Bouaichoune", "Bouchrahil", "Boughezoul", "Bouskene", "Chahbounia", "Chellalet El Adhaoura", "Cheniguel (Non livrable)", "Derrag", "Deux Bassins", "Djouab", "Draa Essamar", "El Azizia", "El Guelb El Kebir", "El Hamdania", "El Omaria", "El Ouinet", "Hannacha", "Kef Lakhdar", "Khams Djouamaa", "Ksar Boukhari", "Médéa", "Meftaha", "Meghraoua", "Mezerana", "Mihoub", "Moudjbar", "Ouamri", "Oued Harbil", "Ouled Antar", "Ouled Bouachra", "Ouled Brahim 26", "Ouled Deide", "Ouled Hellal", "Ouled Maaref", "Oum El Djalil", "Ouzera", "Rebaia", "Saneg", "Sedraia", "Seghouane", "Si Mahdjoub", "Sidi Damed", "Sidi Errabia", "Sidi Naamanez", "Sidi Zahar", "Sidi Ziane", "Souagui", "Tablat", "Tafraout", "Tamesguida", "Tizi Mahdi", "Tlatet Eddouar", "Zoubiria"],
			"27- Mostaganem": ["Choisir Commune", "Abdelmalek Ramdane", "Achaacha", "Aïn Boudinar", "Aïn Nouissy", "Aïn Sidi Cherif", "Aïn Tedles", "Blad Touahria", "Bouguirat", "El Hassaine", "Fornaka", "Hadjadj", "Hassi Mameche", "Khadra", "Kheireddine", "Mansourah 27", "Mazagran", "Mesra", "Mostaganem", "Nekmaria", "Oued El Kheir", "Ouled Boughalem", "Ouled Maallah (Non livrable)", "Safsaf", "Sayada", "Sidi Ali", "Sidi Belattar (Non livrable)", "Sidi Lakhdar 27", "Sirat", "Souaflia", "Sour", "Stidia", "Tazgait"],
			"28- M'sila":["Choisir Commune", "Aïn El Hadjel", "Aïn El Melh", "Aïn Errich", "Aïn Fares 28", "Aïn Khadra", "Belaiba", "Ben Srour", "Beni Ilmane", "Benzouh", "Berhoum", "Bir Foda", "Bou Saâda", "Bouti Sayah", "Chellal", "Dehahna", "Djebel Messaad", "El Hamel", "El Houamed", "Hammam Dhalaa", "Khettouti Sed El Djir", "Khoubana", "M'Cif", "M'Sila", "M'Tarfa", "Maadid", "Maarif", "Magra", "Medjedel", "Mohammed Boudiaf", "Ouanougha", "Ouled Addi Guebala", "Ouled Atia", "Ouled Derradj", "Ouled Madhi", "Ouled Mansour", "Ouled Sidi Brahim 28", "Ouled Slimane", "Oultem", "Sidi Aïssa", "Sidi Ameur", "Sidi Hadjeres", "Sidi M'Hamed 28", "Slim", "Souamaa", "Tamsa", "Tarmount", "Zarzour"],
			"29- Mascara": ["Choisir Commune", "Aïn Fares 29", "Aïn Fekan", "Aïn Ferah", "Aïn Fras", "Alaïmia", "Aouf", "Beniane", "Bou Hanifia", "Bou Henni", "Chorfa 29", "El Bordj", "El Gaada", "El Ghomri", "El Guettana", "El Keurt", "El Menaouer", "Ferraguig", "Froha", "Gharrous", "Ghriss", "Guerdjoum", "Hachem", "Hacine", "Khalouia", "Makdha", "Mamounia", "Maoussa", "Mascara", "Matemore", "Mocta Douz", "Mohammadia 29", "Nesmoth", "Oggaz", "Oued El Abtal", "Oued Taria", "Ras El Aïn Amirouche", "Sedjerara", "Sehailia", "Sidi Abdeldjebar", "Sidi Abdelmoumen", "Sidi Boussaid", "Sidi Kada", "Sig", "Tighennif", "Tizi", "Zahana", "Zelmata"],
			"30- Ouargla": ["Choisir Commune", "Aïn Beida", "El Borma (Non livrable)", "Hassi Ben Abdellah", "Hassi Messaoud", "N'Goussa", "Ouargla", "Rouissat", "Sidi Khouiled"],
			"31- Oran": ["Choisir Commune", "Aïn El Bia", "Aïn El Kerma", "Aïn El Turk", "Arzew", "Ben Freha", "Bethioua", "Bir El Djir", "Bou Sfer", "Boufatis", "Boutlelis", "El Ançor", "El Braya", "El Kerma", "Es Senia", "Gdyel", "Hassi Ben Okba", "Hassi Bounif", "Hassi Mefsoukh", "Marsat El Hadjadj", "Mers El Kébir", "Misserghin", "Oran", "Oued Tlelat", "Sidi Benyebka", "Sidi Chami", "Tafraoui",],	
			"32- El Bayadh": ["Choisir Commune", "Aïn El Orak", "Arbaouat", "Boualem", "Bougtoub", "Boussemghoun", "Brezina", "Cheguig (Non livrable)","Chellala", "El Abiodh Sidi Cheikh", "El Bayadh", "El Bnoud (Non livrable)", "El Kheiter", "El Mehara", "Ghassoul", "Kef El Ahmar", "Kraakda (Non livrable)", "Rogassa", "Sidi Ameur (Non livrable)", "Sidi Slimane (Non livrable)", "Sidi Tifour", "Stitten", "Tousmouline (Non livrable)"],
			"33- Illizi": ["Choisir Commune", "Bordj Omar Driss (Non livrable)", "Debdeb (Non livrable)", "Illizi", "In Amenas"],	
			"34- Bordj Bou Arreridj": ["Choisir Commune", "Aïn Taghrout", "Aïn Tesra", "Belimour", "Ben Daoud", "Bir Kasdali", "Bordj Bou Arreridj", "Bordj Ghédir", "Bordj Zemoura", "Colla", "Djaafra", "El Ach", "El Achir", "El Anseur", "El Hamadia", "El M'hir", "El Main", "Ghilassa", "Haraza", "Hasnaoua", "Khelil", "Ksour", "Mansoura 34", "Medjana", "Ouled Brahem", "Ouled Dahmane", "Ouled Sidi Brahim 34", "Rabta", "Ras El Oued", "Sidi Embarek", "Taglait", "Tassameurt", "Tefreg", "Teniet En Nasr", "Tixter"],	
			"35- Boumerdès": ["Choisir Commune", "Afir", "Ammal", "Baghlia", "Ben Choud", "Beni Amrane", "Bordj Menaiel", "Boudouaou", "Boudouaou El Bahri", "Boumerdes", "Bouzegza Keddara", "Chabet el Ameur", "Corso", "Dellys", "Djinet", "El Kharrouba", "Hammedi", "Issers", "Khemis El Khechna", "Larbatache", "Leghata", "Naciria", "Ouled Aissa", "Ouled Hedadj", "Ouled Moussa", "Si Mustapha", "Sidi Daoud", "Souk El Had 35", "Taourga", "Thenia", "Tidjelabine", "Timezrit 35", "Zemmouri"],
			"36- El Tarf": ["Choisir Commune", "Aïn El Assel", "Aïn Kerma", "Asfour", "Ben Mehidi", "Berrihane", "Besbes", "Bougous", "Bouhadjar", "Bouteldja", "Chebaita Mokhtar", "Chefia", "Chihani", "Dréan", "Echatt", "El Aioun", "El Kala", "El Tarf", "Hammam Beni Salah", "Lac des Oiseaux", "Oued Zitoun", "Raml Souk", "Souarekh", "Zerizer", "Zitouna"],
			"37- Tindouf": ["Choisir Commune", "Oum el Assel", "Tindouf"],
			"38- Tissemsilt": ["Choisir Commune", "Ammari", "Beni Chaib (Non livrable)", "Beni Lahcene (Non livrable)", "Bordj Bou Naama", "Bordj El Emir Abdelkader", "Boucaid", "Khemisti 38", "Larbaa (Non livrable)", "Lardjem", "Layoune", "Lazharia", "Maacem", "Melaab", "Ouled Bessem", "Sidi Abed (Non livrable)", "Sidi Boutouchent (Non livrable)", "Sidi Lantri", "Sidi Slimane", "Tamalaht", "Theniet El Had", "Tissemsilt", "Youssoufia"],
			"39- El Oued": ["Choisir Commune", "Bayadha", "Beni Guecha", "Debila", "Douar El Ma", "El Ogla 39", "El Oued", "Guemar", "Hamraia", "Hassani Abdelkrim", "Hassi Khalifa", "Kouinine", "Magrane", "Mih Ouansa", "Nakhla", "Oued El Alenda", "Ourmas", "Reguiba", "Robbah", "Sidi Aoun", "Taghzout 39", "Taleb Larbi", "Trifaoui"],
			"40- Khenchela": ["Choisir Commune", "Aïn Touila", "Babar", "Baghai", "Bouhmama", "Chechar", "Chelia", "Djellal (Non livrable)", "El Hamma", "El Mahmal", "El Oueldja", "Ensigha", "Kais", "Khenchela", "Khirane (Non livrable)", "M'Sara", "M'Toussa", "Ouled Rechache", "Remila", "Tamza", "Taouzient", "Yabous"],	
			"41- Souk Ahras": ["Choisir Commune", "Aïn Soltane (Non livrable)", "Aïn Zana", "Bir Bou Haouch", "Drea", "Hanancha", "Heddada", "Khedara", "Khemissa", "M'daourouch", "Mechroha", "Merahna", "Oued Keberit (Non livrable)", "Ouillen", "Ouled Driss", "Ouled Moumene (Non livrable)", "Oum El Adhaim (Non livrable)", "Ragouba", "Safel El Ouiden (Non livrable)", "Sedrata", "Sidi Fredj", "Souk Ahras", "Taoura", "Terraguelt (Non livrable)", "Tiffech", "Zaarouria", "Zouabi"],
			"42- Tipaza": ["Choisir Commune", "Aghbal", "Ahmar El Aïn", "Aïn Tagourait", "Attatba", "Beni Milleuk", "Bou Ismaïl", "Bouharoun", "Bourkika", "Chaiba", "Cherchell", "Damous", "Douaouda", "Fouka", "Gouraya", "Hadjeret Ennous", "Hadjout", "Khemisti 42", "Koléa", "Larhat", "Menaceur", "Merad", "Messelmoun", "Nador", "Sidi Amar 42", "Sidi Ghiles", "Sidi Rached", "Sidi Semiane", "Tipaza"],
			"43- Mila": ["Choisir Commune", "Ahmed Rachedi", "Aïn Beida Harriche", "Aïn Mellouk", "Aïn Tine", "Amira Arrès", "Benyahia Abderrahmane", "Bouhatem", "Chelghoum Laid", "Chigara (Non livrable)", "Derradji Bousselah (Non livrable)", "El Mechira", "Elayadi Barbes (Non livrable)", "Ferdjioua", "Grarem Gouga", "Hamala", "Mila", "Minar Zarza (Non livrable)", "Oued Athmania", "Oued Endja", "Oued Seguen", "Ouled Khalouf", "Rouached", "Sidi Khelifa", "Sidi Merouane", "Tadjenanet", "Tassadane Haddada (Non livrable)", "Teleghma", "Terrai Bainen (Non livrable)", "Tessala Lemtaï (Non livrable)", "Tiberguent (Non livrable)", "Yahia Beni Guecha", "Zeghaia"],
			"44- Aïn Defla": ["Choisir Commune", "Aïn Benian 44", "Aïn Bouyahia", "Aïn Defla", "Aïn Lechiekh", "Aïn Soltane 44", "Aïn Torki", "Arib", "Bathia (Non livrable)", "Belaas (Non livrable)", "Ben Allal", "Bir Ould Khelifa", "Birbouche", "Bordj Emir Khaled", "Boumedfaa", "Bourached", "Djelida", "Djemaa Ouled Cheikh (Non livrable)", "Djendel", "El Abadia", "El Amra", "El Attaf", "El Hassania (Non livrable)", "El Maine (Non livrable)", "Hammam Righa", "Hoceinia", "Khemis Miliana", "Mekhatria", "Miliana", "Oued Chorfa", "Oued Djemaa", "Rouina", "Sidi Lakhdar 44", "Tacheta Zougagha", "Tarik Ibn Ziad", "Tiberkanine", "Zeddine"],
			"45- Naâma": ["Choisir Commune", "Aïn Ben Khelil", "Aïn Sefra", "Assela", "Djeniene Bourezg", "El Biod", "Kasdir (Non livrable)", "Makman Ben Amer", "Mecheria", "Moghrar", "Naâma", "Sfissifa", "Tiout"],
			"46- Aïn Témouchent": ["Choisir Commune", "Aghlal", "Aïn El Arbaa", "Aïn Kihal", "Aïn Témouchent", "Aïn Tolba", "Aoubellil", "Beni Saf", "Bouzedjar", "Chaabat El Leham", "Chentouf", "El Amria", "El Emir Abdelkader", "El Malah", "El Messaid", "Hammam Bouhadjar", "Hassasna", "Hassi El Ghella", "Oued Berkeche", "Oued Sabah", "Ouled Boudjemaa", "Ouled Kihal", "Oulhaça El Gheraba", "Sidi Ben Adda", "Sidi Boumedienne", "Sidi Ouriache", "Sidi Safi", "Tamzoura", "Terga"],
			"47- Ghardaïa": ["Choisir Commune", "Berriane", "Bounoura", "Dhayet Bendhahoua", "El Atteuf", "El Guerrara", "Ghardaïa", "Mansoura 47", "Metlili", "Sebseb", "Zelfana"],
			"48- Relizane": ["Choisir Commune", "Aïn Rahma", "Aïn Tarek", "Ammi Moussa", "Belassel Bouzegza", "Bendaoud", "Beni Dergoun", "Beni Zentis", "Dar Ben Abdellah", "Djidioua", "El Guettar", "El Hamadna", "El Hassi", "El Matmar", "El Ouldja 48", "Had Echkalla", "Hamri", "Kalaa", "Lahlef", "Mazouna", "Mediouna", "Mendes", "Merdja Sidi Abed", "Ouarizane", "Oued El Djemaa", "Oued Essalem", "Oued Rhiou", "Ouled Aiche", "Ouled Sidi Mihoub", "Ramka", "Relizane", "Sidi Khettab", "Sidi Lazreg", "Sidi M'Hamed Ben Ali", "Sidi M'Hamed Benaouda", "Sidi Saada", "Souk El Had 48", "Yellel", "Zemmora"],
			"49- Timimoun": ["Choisir Commune", "Aougrout", "Charouine", "Deldoul", "Ksar Kaddour", "Metarfa", "Ouled Aïssa", "Ouled Saïd", "Talmine", "Timimoun", "Tinerkouk"],
			"50- Bordj Badji Mokhtar": ["Choisir Commune", "Bordj Badji Mokhtar (Non livrable)", "Timiaouine (Non livrable)"],
			"51- Ouled Djellal": ["Choisir Commune", "Besbes (Non livrable)", "Ech Chaïba", "Doucen", "Ouled Djellal", "Sidi Khaled", "Ras El Miaad (Non livrable)"],
			"52- Béni Abbès": ["Choisir Commune", "Béni Abbès", "Beni Ikhlef", "El Ouata", "Igli", "Kerzaz", "Ksabi", "Ouled Khoudir", "Tabelbala (Non livrable)", "Tamtert", "Timoudi"],
			"53- In Salah": ["Choisir Commune", "Foggaret Ezzaouia (Non livrable)", "In Ghar (Non livrable)", "In Salah"],
			"54- In Guezzam": ["Choisir Commune", "In Guezzam  (Non livrable)", "Tin Zaouatine  (Non livrable)"],
			"55- Touggourt": ["Choisir Commune", "Benaceur", "Blidet Amor", "El Allia (Non livrable)", "El Hadjira (Non livrable)", "Megarine", "M'Naguer", "Nezla", "Sidi Slimane", "Taibet", "Tamacine", "Tebesbest", "Touggourt", "Zaouia El Abidia"],
			"56- Djanet": ["Choisir Commune", "Djanet", "Bordj El Haouas"],
			"57- El M’Ghaier": ["Choisir Commune", "Djamaa", "El M'Ghair", "M'Rara", "Oum Touyour", "Sidi Amrane", "Sidi Khellil", "Still", "Tendla"],
			"58- EL Meniaa": ["Choisir Commune", "EL Meniaa", "Hassi Fehal", "Hassi Gara"],	
						
            };

            // Insérer les nouvelles options de commune
            communes[selectedWilaya].forEach(function(commune) {
                const option = document.createElement("option");
                option.text = commune;
                option.value = commune;
                communeSelect.add(option);
            });
        }

        // Appelez chargerCommunes() une fois au chargement de la page pour afficher les communes initiales
        chargerCommunes();
